spring.application.name=meal-planner

# default profile
spring.profiles.active=dev
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#	ddl-auto=update # dev Fast iteration
#	ddl-auto=create-drop # test Clean DB