INSERT INTO RECIPE (NAME, MEAL_TYPE) VALUES ('Omelette', 'BREAKFAST');
INSERT INTO RECIPE (NAME, MEAL_TYPE) VALUES ('Pancakes', 'BREAKFAST');
INSERT INTO RECIPE (NAME, MEAL_TYPE) VALUES ('Grilled Chicken Salad', 'LUNCH');
INSERT INTO RECIPE (NAME, MEAL_TYPE) VALUES ('Cottage Cheese', 'LATE_NIGHT_SNACK');
INSERT INTO RECIPE (NAME, MEAL_TYPE) VALUES ('Spaghetti Bolognese', 'DINNER');

--see all the recipes you inserted:
SELECT * FROM RECIPE;